### ISSUE TITLE
[request] : Frontend

### ISSUE THREAD

**Issue by leolab1337** [Alt-Org/Altzone-Server#3] opened 2023-10-02 10:07 UTC
Frontend requires to have an endpoint for serving images by categories with metadata.

Desired format: 

```json
[
    {
        "categoryName": "Cats",
        "images": [
            {
                "src": "server/img/Cats/funnyCat",
                "name": "Funny Cat",
                "description": "Cat makes mems"
            },
            {
                 //... other image data
            }
        ]
    }, 
    {
        "categoryName": "Dogs",
        "images": [
            {
                "src": "server/img/Dogs/funnyDog",
                "name": "Funny Dog",
                "description": "Dog makes mems"
            },
            {
                 //... other image data
            }
        ]
    }
]

**Comment by MikhailDeriabin** [comment] 2023-10-04 13:54
I will look into it in the near future

**Comment by MikhailDeriabin** [comment] 2023-10-05 14:29
Status update:
Images info can be accessed via /public/site endpoint (GET), which is a folder on the server. You will get the list of the all folders and files:
```
[
{ "name":"comics", "type":"directory", "mtime":"Thu, 05 Oct 2023 13:42:03 GMT" },
{ "name":"images", "type":"directory", "mtime":"Thu, 05 Oct 2023 13:42:03 GMT" }
]
```

The folder name may represent the image category and image name can be obtained from file name. 
However, description and other possible metadata probably should be added with UI or manually, since the server can not do it automatically. I will discuss this feature with my colleagues and add description to documentation.
If you have no more questions please close the issue

**Comment by leolab1337** [comment] 2023-10-05 14:59
Thanks for the feature. Accessibility is something we should prioritize, so I think adding them manually is a good idea initially. Later, we could consider a global admin panel to handle such tasks more comfortably. I close the issue

**Comment by leolab1337** [comment] 2023-10-06 08:38
Hello, is it possible to add an extra folder layer, in order to have groups of pictures, e.g. https://altzone.fi/public/site/{folderPicturesByArtist}/{folderwithArtistname}/{myfirstart.png}

**Comment by MikhailDeriabin** [comment] 2023-10-06 12:12
Yes, it is possible as long as it fits frontend needs. Currently these files are served by nginx, which provides all of the file system structure info automaticly

**Comment by leolab1337** [comment] 2023-10-06 13:21
nice!

**Comment by leolab1337** [comment] 2023-10-28 14:20
hello, the current solution has a problem with cors : "missing allow origin header"

**Comment by MikhailDeriabin** [comment] 2023-11-02 13:10
The issue is now fixed

**Closed by MikhailDeriabin** 2023-11-02 13:10 UTC
Labels: enhancement
